### ISSUE TITLE
Doesn't install on a vagrant mounted share if host is windows

### ISSUE THREAD

**Issue by LudwigHoff** [pierreinglebert/node-zopfli#15]
Hey

Works like a charm on my mac.  Thank you very much for this module.

But my colleagues who are running their vagrant VM on windows get this:

npm ERR! Error: UNKNOWN, symlink '../node-pre-gyp/bin/node-pre-gyp'

This is with the --no-bin-links flag set.

Cheers

N

**Comment by pierreinglebert** [comment]
Hi,

Can you try ```npm install node-zopfli@dev``` ?

**Comment by LudwigHoff** [comment]
Will try now.  Thank you.

**Comment by LudwigHoff** [comment]
Worked awesomely (with --no-bin-links):
 
node-zopfli@1.2.3 node_modules/node-zopfli
├── commander@2.5.1
├── buffer-crc32@0.2.5
├── async@0.9.0
├── nan@1.4.3
├── bluebird@2.3.11
└── node-pre-gyp@0.5.31

**Comment by pierreinglebert** [comment]
Nice, I will publish it later (this week-end most likely), i have to rebuild .dll for windows users, in the meanwhile, you can use the @dev

**Comment by LudwigHoff** [comment]
You are a gent.
