### ISSUE TITLE
Build failure on Ununtu 14.10

### ISSUE THREAD

**Issue by popkinj** [pierreinglebert/node-zopfli#20]
After my latest software update *node-zopfli* is failing to build. I can't seem to track down the source of the problem. The regular command line package for zopfli is fine (not sure if they are connected).

Wondering if these lines are of any help:
```
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:340:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 3.13.0-48-generic
```
One thing that strikes me is the build script is running *node-gyp* from my system-wide /usr/lib/ directory... Which shouldn't be used any more. Or at least I thought I over rode that a while ago 😐. I use [nvm](https://github.com/creationix/nvm) to manage all my *node/io* versions. Shouldn't it be calling *gyp* from there?

Something like:
> /home/me/.nvm/versions/node/v0.12.1/lib/node_modules/npm/node_modules/node-gyp

Not sure if that helps. Let me know if posting the full *npm-debug.log* file would help.

**Comment by pierreinglebert** [comment]
I couldnt reproduce on an ubuntu 14.10 with nvm & 0.12.1. It's probably a bug within node-pre-gyp, if you don't use anymore your distro node, uninstall it, hopefully it will clean your /usr/lib directory.

**Comment by popkinj** [comment]
Thanks for testing Pierre. Will do. ☺

**Comment by pierreinglebert** [comment]
I think I'm going to drop node-pre-gyp and use directly node-gyp, it will stop support on windows not capable to compile but I dont think that's many users.

**Comment by popkinj** [comment]
Sounds like a fairly sane direction. Less dependencies makes things less brittle.

**Comment by pierreinglebert** [comment]
With the new version (1.3.2), you should no more have a build step !
I tried on an ubuntu 15.04 x64 :)
