### ISSUE TITLE
Build fail on windows_NT 6.17601

### ISSUE THREAD

**Issue by chenxiaochun** [pierreinglebert/node-zopfli#21]
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at errnoException (net.js:905:11)
gyp ERR! stack     at TCP.onread (net.js:559:19)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "c:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Adminis
trator.BJXX-20140703IN\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node
-gyp.js" "configure" "--fallback-to-build" "--build-from-source" "--module=C:\\U
sers\\Administrator.BJXX-20140703IN\\AppData\\Roaming\\npm\\node_modules\\node-z
opfli\\lib\\binding\\node-v11-win32-x64\\zopfli.node" "--module_name=zopfli" "--
module_path=C:\\Users\\Administrator.BJXX-20140703IN\\AppData\\Roaming\\npm\\nod
e_modules\\node-zopfli\\lib\\binding\\node-v11-win32-x64"
gyp ERR! cwd C:\Users\Administrator.BJXX-20140703IN\AppData\Roaming\npm\node_mod
ules\node-zopfli
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'c:\Program Files (x86)\nodejs\
node.exe C:\Users\Administrator.BJXX-20140703IN\AppData\Roaming\npm\node_modules
\node-gyp\bin\node-gyp.js configure --fallback-to-build --build-from-source --mo
dule=C:\Users\Administrator.BJXX-20140703IN\AppData\Roaming\npm\node_modules\nod
e-zopfli\lib\binding\node-v11-win32-x64\zopfli.node --module_name=zopfli --modul
e_path=C:\Users\Administrator.BJXX-20140703IN\AppData\Roaming\npm\node_modules\n
ode-zopfli\lib\binding\node-v11-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Administrator.
BJXX-20140703IN\AppData\Roaming\npm\node_modules\node-zopfli\node_modules\node-p
re-gyp\lib\util\compile.js:73:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:766:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_proces
s.js:833:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "node" "C:\\Users\\Administrator.BJXX-20140703IN\\AppD
ata\\Roaming\\npm\\node_modules\\node-zopfli\\node_modules\\node-pre-gyp\\bin\\n
ode-pre-gyp" "install" "--fallback-to-build" "--build-from-source"
node-pre-gyp ERR! cwd C:\Users\Administrator.BJXX-20140703IN\AppData\Roaming\npm
\node_modules\node-zopfli
node-pre-gyp ERR! node -v v0.10.35
node-pre-gyp ERR! node-pre-gyp -v v0.6.4
node-pre-gyp ERR! not ok
Failed to execute 'c:\Program Files (x86)\nodejs\node.exe C:\Users\Administrator
.BJXX-20140703IN\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js confi
gure --fallback-to-build --build-from-source --module=C:\Users\Administrator.BJX
X-20140703IN\AppData\Roaming\npm\node_modules\node-zopfli\lib\binding\node-v11-w
in32-x64\zopfli.node --module_name=zopfli --module_path=C:\Users\Administrator.B
JXX-20140703IN\AppData\Roaming\npm\node_modules\node-zopfli\lib\binding\node-v11
-win32-x64' (1)

npm ERR! node-zopfli@1.2.6 install: `node-pre-gyp install --fallback-to-build --
build-from-source`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-zopfli@1.2.6 install script.
npm ERR! This is most likely a problem with the node-zopfli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build --build-from-source
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-zopfli
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Program Files (x86)\\nodejs\\node.exe" "c:\\Program Files
(x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-zopfli" "-g"
npm ERR! cwd D:\Test
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by pierreinglebert** [comment]
It seems to be a network error, the 3rd line is : "gyp ERR! stack Error: read ECONNRESET"

**Comment by pierreinglebert** [comment]
btw, with the last version published (1.3.2) will fix your issue as gyp wont be necessary :)
