### ISSUE TITLE
Fail to download 1.3.3

### ISSUE THREAD

**Issue by pierreinglebert** [pierreinglebert/node-zopfli#57]
@artem-popov : What issue do you have with 1.3.3 that made you create [this](https://github.com/SelfishInc/gulp-zopfli) fork this repo ?

**Comment by artem-popov** [comment]
Now I use npm shrinkwrap, so my fork is not neccessary - it was an ugly hack because I was need to deploy my app. 

Possibly it was temporary unavailable. npm was unable to download it.
