### ISSUE TITLE
Error: Cannot find module '/home/hugomrdias/code/movves/node_modules/node-zopfli/lib/binding/node-v47-linux-x64/zopfli.node'] code: 'MODULE_NOT_FOUND'

### ISSUE THREAD

**Issue by hugomrdias** [pierreinglebert/node-zopfli#66]
npm install built `/lib/binding/node-v45-darwin-x64/zopfli.node` not v47 

node 5.6.0
npm 3.7.3

on mint LTS

**Comment by pierreinglebert** [comment]
did you run `npm rebuild` after upgrading from node v4 to node v5 ?
