### ISSUE TITLE
Installation fails on CentOS 32-bit (i686), node v4.4.2, npm v2.15.0

### ISSUE THREAD

**Issue by carpusmedia** [pierreinglebert/node-zopfli#73]
Hello,

We are having difficulties installing node-zopfli on _CentOS 32-bit (i686)_ with _node_ at _4.4.2_ and _npm_ at _2.15.0_.

This is an excerpt of the error message:
```
npm ERR! Linux 2.6.32-042stab113.21
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--unsafe-perm"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0
npm ERR! code ELIFECYCLE
npm ERR! node-zopfli@1.4.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-zopfli@1.4.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the node-zopfli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-zopfli
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls node-zopfli
npm ERR! There is likely additional logging output above.

```
Attached is the rest of the CLI output, along with the npm_debug.log.

[npm_debug.log.zip](https://github.com/pierreinglebert/node-zopfli/files/370945/npm_debug.log.zip)

[CLI_output.zip](https://github.com/pierreinglebert/node-zopfli/files/370946/CLI_output.zip)

**Comment by pierreinglebert** [comment]
At the 10th line of CLI_output : 
../node_modules/nan/nan.h:43:3: error: #error This version of node/NAN/v8 requires a C++11 compiler

:)

**Comment by carpusmedia** [comment]
Aah, of course! Installing a C++11 compiler solved the problem.

Thank you.
