### ISSUE TITLE
Error downloading release

### ISSUE THREAD

**Issue by youngcm2** [pierreinglebert/node-zopfli#76]
https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v46-win32-x64.tar.gz

When trying to download the release we get an access denied. 

Error in npm
![screen shot 2016-08-12 at 3 56 58 pm](https://cloud.githubusercontent.com/assets/862338/17636873/b46bdf6c-60a5-11e6-8aac-17108f1680be.png)

Error trying from Chrome
<img width="1000" alt="screen shot 2016-08-12 at 3 56 38 pm" src="https://cloud.githubusercontent.com/assets/862338/17636880/c3b99842-60a5-11e6-9b07-3450b4b57224.png">

**Comment by pierreinglebert** [comment]
That's because prebuilt binaries (it's just for win users who dont' have a c++ compiler) are built when I publish a new version, in this case '1.4.0' and that was just before node 4 was out so there isnt prebuilt binary for it.
I'll check if i can do that easily, in the meantime, you can try v2.0 :)

**Comment by ortreum** [comment]
Hi, I would do it if I could. But there is the same error. 
node-pre-gyp ERR! Tried to download: https://node-zopfli.s3.amazonaws.com/Release/zopfli-v2.0.0-node-v48-linux-x64.tar.gz
I think there is a permission problem.

npm i angular-cli@lastest -g downloads the latest version of zopfli. I can not say @2.0.0 or below.

Michael

**Comment by pierreinglebert** [comment]
Hi,
On linux, this is a normal behaviour, there are too many different gcc & lib versions to handle. It will compile for your specific platform so you must have python, gcc and make.

**Comment by ortreum** [comment]
Hi,

I did:
apt-get install gcc make python
Nothing new was installed.

make: Entering directory `/usr/lib/node_modules/zopfli/build'
  CXX(target) Release/obj.target/zopfli/src/zopfli.o
In file included from ../src/zopfli.cc:9:0:
../src/v8u.hpp:86:43: error: ‘Arguments’ in namespace ‘v8’ does not name a type
 inline void CheckArguments(int min, const v8::Arguments& args) {
[...tons of stack trace...]
In file included from ../src/zopfli.cc:9:0:
../src/v8u.hpp: In function ‘v8::Local<v8::String> v8u::Symbol(const char*, int)’:
../src/v8u.hpp:310:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make: *** [Release/obj.target/zopfli/src/zopfli.o] Error 1
make: Leaving directory `/usr/lib/node_modules/zopfli/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2

**Comment by pierreinglebert** [comment]
Can you give me the node & gcc versions ?

**Comment by ortreum** [comment]
If you think npm i npm@latest -g updates your npm then you are mistaken ... :( I still had npm 3.10.8. Sorry. Solved.

**Comment by kunyan** [comment]
2.0.1 still has same issue https://node-zopfli.s3.amazonaws.com/Release/zopfli-v2.0.1-node-v48-linux-x64.tar.gz

AccessDenied

**Comment by pierreinglebert** [comment]
It's normal, there are no prebuilt binaries for linux (too many different env).
