### ISSUE TITLE
npm install node-zopfli failed

### ISSUE THREAD

**Issue by rayeesoft** [pierreinglebert/node-zopfli#79]
```
[root@localhost node-zopfli]# cnpm install
node-pre-gyp http GET https://node-zopfli.s3.amazonaws.com/Release/zopfli-v2.0.1-node-v48-linux-x64.tar.gz
node-pre-gyp http 403 https://node-zopfli.s3.amazonaws.com/Release/zopfli-v2.0.1-node-v48-linux-x64.tar.gz
node-pre-gyp ERR! Tried to download(403): https://node-zopfli.s3.amazonaws.com/Release/zopfli-v2.0.1-node-v48-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@2.0.1 and node@6.9.1 (node-v48 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http 403 status code downloading tarball https://node-zopfli.s3.amazonaws.com/Release/zopfli-v2.0.1-node-v48-linux-x64.tar.gz
make: Entering directory `/opt/node/lib/node_modules/node-zopfli/build'
  CXX(target) Release/obj.target/zopfli/src/zopfli-binding.o
In file included from ../src/zopfli-binding.h:5,
                 from ../src/zopfli-binding.cc:3:
../node_modules/.2.4.0@nan/nan.h:43:3: error: #error This version of node/NAN/v8 requires a C++11 compiler
In file included from /root/.node-gyp/6.9.1/include/node/node.h:42,
                 from ../src/zopfli-binding.cc:1:
```
Python 2.7.6
gcc version 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC)
node v6.9.1
npm 3.10.8

**Comment by pierreinglebert** [comment]
../node_modules/.2.4.0@nan/nan.h:43:3: error: #error This version of node/NAN/v8 requires a C++11 compiler

Try with gcc 4.9+ :)

**Comment by nnguyen** [comment]
Hi @pierreinglebert, 
Is it possible to get a precompile version for node@6.9.1 on s3? It would greatly help me out given the pain in getting gcc 4.9+ in my current environment.  TIA!

**Comment by pierreinglebert** [comment]
On linux, this is not currently possible because the current system is not precise enough, I can only build for platforms (linux, win, osx). But libraries are not located on the same place between linux distributions, so if I build the linux binary on a debian, it wont work on redhat, archlinux, etc.

**Comment by pierreinglebert** [comment]
The newest version doesn't use aws anymore but Github to store binary packages.
