### ISSUE TITLE
Dont install zopfli during npm install if binary available.

### ISSUE THREAD

**Issue by rparjun** [pierreinglebert/node-zopfli#81]
Thanks for the awesome package. Im using this package to compress frontend assets generated using Webpack.
Each time when the package is installed it installs zopfli binary also which slows the entire process.
Is there any way to skip installation of binary(checking if the binary is already available in the machine)?

**Comment by pierreinglebert** [comment]
The only way to do something like that would be to install node-zopfli globally on your computer with the -g option.

**Comment by rparjun** [comment]
Im using webpack compression plugin, which is having node-zopfli as a dependency, so im not having control over the installation, and zopfli will be installed during npm install even if it is globally available.

https://github.com/webpack/compression-webpack-plugin/blob/master/package.json

**Comment by pierreinglebert** [comment]
During the packages installation, you have no knowledge of other installations you may have somewhere else on your computer.

The only possible solution would be to publish the tar.gz of your "zopfli.node" on a http server and to use "--node-zopfli_binary_host_mirror" during install.
The path on the web server will something like be "/node-zopfli/v2.0.0/node-v48-linux-x64.tar.gz" (you can find it the right one in installation logs).
https://www.npmjs.com/package/node-pre-gyp#download-binary-files-from-a-mirror

**Comment by rparjun** [comment]
Thanks @pierreinglebert, I will try it out later. Moved to Yarn and was able to install the whole package.json in 20 to 30 seconds where NPM was taking more than a minute!!.
Also the output was less verbose, all the warning message while installing the binary was not shown.
