### ISSUE TITLE
custom url needed to download pre-built zopfli binaries

### ISSUE THREAD

**Issue by vinothvk** [pierreinglebert/node-zopfli#89]
Can you please provide a custom URL functionality to download the zopfli pre-built binaries from internally hosted node registry rather from external amazon url ? Corporate proxies doesn't allow downloading of binaries from external URLs. 

Phantom JS pre built binaries are allowed to be hosted in internal repository
https://www.npmjs.com/package/phantomjs-prebuilt#downloading-from-a-custom-url

**Comment by pierreinglebert** [comment]
Binaries are now downloaded from Github, if you dont have access to Github on your servers, you can look at the doc of https://github.com/prebuild/prebuild-install 
You can set a custom URL :)
