### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by oscardalence** [pierreinglebert/node-zopfli#90]
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-zopfli@1.4.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-zopfli@1.4.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure 

you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-zopfli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-zopfli
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-zopfli
npm ERR! There is likely additional logging output above.

NOTE: There are no log file

**Comment by treefort** [comment]
I'm having the same issue. Is this project still alive?

**Comment by JosefJezek** [comment]
This repo has binaries

https://github.com/bruce-one/node-zopfli/releases

`npm install -g bruce-one/node-zopfli`

**Comment by Kamill90** [comment]
that's not working for me. 
W10
node 8.9 
npm 4

**Comment by happyyangyuan** [comment]
@JosefJezek 
node-pre-gyp ERR! Tried to download(404): https://github.com/bruce-one/node-zopfli/releases/download/2.0.2/zopfli-v2.0.2-node-v57-darwin-x64.tar.gz 

Trying to get a unexisted version of gz file: zopfli-v2.0.2-node-v57-darwin-x64.tar.gz

**Comment by pierreinglebert** [comment]
Try with the new published v2.0.3
