### ISSUE TITLE
"npm install node-zopfli" fails

### ISSUE THREAD

**Issue by TimMcMSFT** [pierreinglebert/node-zopfli#93]
Perhaps the AWS usage has been exceeded?

npm install node-zopfli

> node-zopfli@1.4.0 install C:\Repos\edgepushsample\node_modules\gulp-zopfli\node_modules\node-zopfli
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@8.11.2 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! configure error

**Comment by boris-petrov** [comment]
@pierreinglebert - I'm receiving the same error. Could you please take a look?

**Comment by pierreinglebert** [comment]
No it was because Node 8 didnt existed when v2.0.2 was out so the binaries were never built and uploaded to AWS.
