### ISSUE TITLE
Binary removed, no node support left with failing builds

### ISSUE THREAD

**Issue by reduxdj** [pierreinglebert/node-zopfli#96]
node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v64-darwin-x64.tar.gz

thanks pierre node zopfli, for removing your binaries, none of my projects build. this is the worst.

**FAIL 🐋**

**Comment by SampsonCrowley** [comment]
Seriously how did you push this to production?

**Comment by alextes** [comment]
Duplicate of #87
